export type CountryCode = {
  code: string
  country: string
  iso: string
}

export const COUNTRY_CODES: CountryCode[] = [
  { code: "+44", country: "United Kingdom", iso: "GB" },
  { code: "+1", country: "United States / Canada", iso: "US" },
  { code: "+353", country: "Ireland", iso: "IE" },
  { code: "+33", country: "France", iso: "FR" },
  { code: "+49", country: "Germany", iso: "DE" },
  { code: "+34", country: "Spain", iso: "ES" },
  { code: "+39", country: "Italy", iso: "IT" },
  { code: "+31", country: "Netherlands", iso: "NL" },
  { code: "+32", country: "Belgium", iso: "BE" },
  { code: "+41", country: "Switzerland", iso: "CH" },
  { code: "+43", country: "Austria", iso: "AT" },
  { code: "+45", country: "Denmark", iso: "DK" },
  { code: "+46", country: "Sweden", iso: "SE" },
  { code: "+47", country: "Norway", iso: "NO" },
  { code: "+48", country: "Poland", iso: "PL" },
  { code: "+351", country: "Portugal", iso: "PT" },
  { code: "+30", country: "Greece", iso: "GR" },
  { code: "+36", country: "Hungary", iso: "HU" },
  { code: "+40", country: "Romania", iso: "RO" },
  { code: "+420", country: "Czech Republic", iso: "CZ" },
  { code: "+358", country: "Finland", iso: "FI" },
  { code: "+380", country: "Ukraine", iso: "UA" },
  { code: "+7", country: "Russia", iso: "RU" },
  { code: "+90", country: "Turkey", iso: "TR" },
  { code: "+61", country: "Australia", iso: "AU" },
  { code: "+64", country: "New Zealand", iso: "NZ" },
  { code: "+27", country: "South Africa", iso: "ZA" },
  { code: "+234", country: "Nigeria", iso: "NG" },
  { code: "+254", country: "Kenya", iso: "KE" },
  { code: "+233", country: "Ghana", iso: "GH" },
  { code: "+20", country: "Egypt", iso: "EG" },
  { code: "+212", country: "Morocco", iso: "MA" },
  { code: "+91", country: "India", iso: "IN" },
  { code: "+92", country: "Pakistan", iso: "PK" },
  { code: "+880", country: "Bangladesh", iso: "BD" },
  { code: "+94", country: "Sri Lanka", iso: "LK" },
  { code: "+86", country: "China", iso: "CN" },
  { code: "+81", country: "Japan", iso: "JP" },
  { code: "+82", country: "South Korea", iso: "KR" },
  { code: "+65", country: "Singapore", iso: "SG" },
  { code: "+60", country: "Malaysia", iso: "MY" },
  { code: "+63", country: "Philippines", iso: "PH" },
  { code: "+66", country: "Thailand", iso: "TH" },
  { code: "+84", country: "Vietnam", iso: "VN" },
  { code: "+62", country: "Indonesia", iso: "ID" },
  { code: "+55", country: "Brazil", iso: "BR" },
  { code: "+52", country: "Mexico", iso: "MX" },
  { code: "+54", country: "Argentina", iso: "AR" },
  { code: "+57", country: "Colombia", iso: "CO" },
  { code: "+56", country: "Chile", iso: "CL" },
  { code: "+971", country: "UAE", iso: "AE" },
  { code: "+966", country: "Saudi Arabia", iso: "SA" },
  { code: "+974", country: "Qatar", iso: "QA" },
  { code: "+972", country: "Israel", iso: "IL" },
  { code: "+1", country: "Jamaica", iso: "JM" },
  { code: "+1", country: "Trinidad & Tobago", iso: "TT" },
]
