// Derives the design-token stylesheet the sync ships under tokens/ from the
// compiled mini-package styles.css. Run from the REPO ROOT after the Tailwind
// compile and before the driver:
//   node .design-sync/build-tokens.mjs
//
// Token rules (user-set, 2026-10-07 - see NOTES.md "Token rules"):
//   1. only custom properties declared under :root / :host / html / [data-*]
//      selectors count as tokens; anything declared only inside utility
//      selectors, nested selectors (:where(& > …)) or @property blocks is left
//      out, and --tw-* is always left out
//   2. --animate-*, --ease-*, --default-*, --aspect-* carry `/* @kind other */`;
//      every --tw-* declaration is stamped `other` too (the app's regeneration
//      of the adherence file ignores tokens/ precedence but reads @kind). A
//      stamp only attaches when the declaration's immediate parent is a token
//      scope or a top-level utility rule whose only ancestors are @layer -
//      never inside a nested @supports/@media or a nested selector, where the
//      app's checker reports the annotation as unattached
//   3. the adherence token list is rebuilt from this file (build-adherence.mjs)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { walkCss, isTokenScope, chainOf } from "./css-walk.mjs";

const PKG = "node_modules/bar-app-ds";
const SRC = `${PKG}/styles.css`;
const OUT = `${PKG}/tokens/tokens.css`;
const OTHER_KIND = /^--(animate|ease|default|aspect)-/;
const STAMP = /^--(animate|ease|default|aspect|tw)-/;

function scan(css) {
  const tokens = [];
  const stamps = [];
  walkCss(css, {
    onDecl: (d) => {
      if (!d.name.startsWith("--")) return;
      const chain = chainOf(d);
      const parent = chain[chain.length - 1] ?? "";
      const outer = chain.slice(0, -1);
      if (!parent || parent.startsWith("@")) return;
      const onlyLayers = outer.every((p) => /^@layer\b/.test(p));
      if (isTokenScope(parent) && !d.name.startsWith("--tw-") && outer.every((p) => p.startsWith("@"))) {
        tokens.push({ chain, name: d.name, value: d.value });
      }
      if (STAMP.test(d.name) && onlyLayers && (isTokenScope(parent) || outer.length <= 1)) {
        stamps.push(d.end);
      }
    },
  });
  return { tokens, stamps };
}

function render(found) {
  const groups = [];
  for (const d of found) {
    const key = d.chain.join(" > ");
    const last = groups[groups.length - 1];
    if (last && last.key === key) last.decls.push(d);
    else groups.push({ key, chain: d.chain, decls: [d] });
  }
  const lines = [
    "/* Design tokens for bar-app-ds - generated by .design-sync/build-tokens.mjs",
    "   from the compiled styles.css. Only :root / [data-*] declarations; Tailwind",
    "   internals and utility-level custom properties are deliberately absent. */",
  ];
  for (const g of groups) {
    g.chain.forEach((p, i) => lines.push(`${"  ".repeat(i)}${p} {`));
    const pad = "  ".repeat(g.chain.length);
    for (const d of g.decls) {
      lines.push(`${pad}${d.name}: ${d.value};${OTHER_KIND.test(d.name) ? " /* @kind other */" : ""}`);
    }
    for (let i = g.chain.length - 1; i >= 0; i--) lines.push(`${"  ".repeat(i)}}`);
  }
  return lines.join("\n") + "\n";
}

function stampInPlace(css, ends) {
  let next = css;
  let stamped = 0;
  for (const end of [...ends].sort((a, b) => b - a)) {
    const after = next.slice(end + 1, end + 24);
    if (/^\s*\/\*\s*@kind/.test(after)) continue;
    next = `${next.slice(0, end + 1)} /* @kind other */${next.slice(end + 1)}`;
    stamped++;
  }
  return { next, stamped };
}

if (process.argv[1] && process.argv[1].endsWith("build-tokens.mjs")) {
  const css = readFileSync(SRC, "utf8");
  const { tokens, stamps } = scan(css);
  mkdirSync(`${PKG}/tokens`, { recursive: true });
  writeFileSync(OUT, render(tokens));
  const { next, stamped } = stampInPlace(css, stamps);
  if (stamped) writeFileSync(SRC, next);
  const names = new Set(tokens.map((d) => d.name));
  const other = tokens.filter((d) => OTHER_KIND.test(d.name)).length;
  console.log(`tokens: ${tokens.length} declarations, ${names.size} names -> ${OUT}; ${other} marked @kind other; ${stamped} stamped in styles.css (${stamps.length} eligible)`);
}
