// Derives the design-token stylesheet the sync ships under tokens/ from the
// compiled mini-package styles.css. Run from the REPO ROOT after the Tailwind
// compile and before the driver:
//   node .design-sync/build-tokens.mjs
//
// Token rules (user-set, 2026-10-07 - see NOTES.md "Token rules"):
//   1. only custom properties declared under :root / :host / html / [data-*]
//      selectors count as tokens; anything declared only inside utility
//      selectors or @property blocks is left out, and --tw-* is always left out
//   2. --animate-*, --ease-*, --default-*, --aspect-* carry `/* @kind other */`
//      (also stamped in place in styles.css so both files agree); every --tw-*
//      declaration in styles.css is stamped `other` too, so the app-side
//      regeneration of the adherence file can never class a Tailwind internal
//      as a colour or spacing (it ignores tokens/ precedence but reads @kind)
//   3. the adherence token list is rebuilt from this file (build-adherence.mjs)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const PKG = "node_modules/bar-app-ds";
const SRC = `${PKG}/styles.css`;
const OUT = `${PKG}/tokens/tokens.css`;
const OTHER_KIND = /^--(animate|ease|default|aspect)-/;

const stripComments = (css) => css.replace(/\/\*[\s\S]*?\*\//g, "");
const isTokenScope = (prelude) =>
  prelude
    .split(",")
    .map((s) => s.trim())
    .every((s) => s === ":root" || s === ":host" || s === "html" || /^\[data-[\w-]+(?:=[^\]]*)?\]$/.test(s) || /^:root\[data-[\w-]+(?:=[^\]]*)?\]$/.test(s));

export function extractTokens(css) {
  const text = stripComments(css);
  const stack = [];
  const found = [];
  let buf = "";
  let quote = null;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (quote) {
      buf += ch;
      if (ch === "\\") { buf += text[++i] ?? ""; continue; }
      if (ch === quote) quote = null;
      continue;
    }
    if (ch === "\\") { buf += ch + (text[++i] ?? ""); continue; }
    if (ch === '"' || ch === "'") { quote = ch; buf += ch; continue; }
    if (ch === "{") { stack.push(buf.trim()); buf = ""; continue; }
    if (ch === ";" || ch === "}") {
      const decl = buf.trim();
      buf = "";
      if (decl.startsWith("--")) {
        const idx = decl.indexOf(":");
        const name = decl.slice(0, idx).trim();
        const value = decl.slice(idx + 1).trim();
        const parent = stack[stack.length - 1] ?? "";
        const outer = stack.slice(0, -1);
        const qualifies =
          !name.startsWith("--tw-") &&
          parent &&
          !parent.startsWith("@") &&
          isTokenScope(parent) &&
          outer.every((p) => p.startsWith("@"));
        if (qualifies) found.push({ chain: [...stack], name, value });
      }
      if (ch === "}") stack.pop();
      continue;
    }
    buf += ch;
  }
  return found;
}

function render(found) {
  const groups = [];
  for (const d of found) {
    const key = d.chain.join(" > ");
    const last = groups[groups.length - 1];
    if (last && last.key === key) last.decls.push(d);
    else groups.push({ key, chain: d.chain, decls: [d] });
  }
  const lines = [
    "/* Design tokens for bar-app-ds - generated by .design-sync/build-tokens.mjs",
    "   from the compiled styles.css. Only :root / [data-*] declarations; --tw-*",
    "   internals and utility-level custom properties are deliberately absent. */",
  ];
  for (const g of groups) {
    g.chain.forEach((p, i) => lines.push(`${"  ".repeat(i)}${p} {`));
    const pad = "  ".repeat(g.chain.length);
    for (const d of g.decls) {
      lines.push(`${pad}${d.name}: ${d.value};${OTHER_KIND.test(d.name) ? " /* @kind other */" : ""}`);
    }
    for (let i = g.chain.length - 1; i >= 0; i--) lines.push(`${"  ".repeat(i)}}`);
  }
  return lines.join("\n") + "\n";
}

function annotateInPlace(css) {
  let stamped = 0;
  const next = css.replace(/^(\s*--(?:animate|ease|default|aspect|tw)-[\w-]+\s*:[^;\n]*;)(?![^\n]*@kind)/gm, (m) => {
    stamped++;
    return `${m} /* @kind other */`;
  });
  return { next, stamped };
}

if (process.argv[1] && process.argv[1].endsWith("build-tokens.mjs")) {
  const css = readFileSync(SRC, "utf8");
  const found = extractTokens(css);
  const names = new Set(found.map((d) => d.name));
  mkdirSync(`${PKG}/tokens`, { recursive: true });
  writeFileSync(OUT, render(found));
  const { next, stamped } = annotateInPlace(css);
  if (stamped) writeFileSync(SRC, next);
  const other = found.filter((d) => OTHER_KIND.test(d.name)).length;
  console.log(`tokens: ${found.length} declarations, ${names.size} names -> ${OUT}; ${other} marked @kind other; ${stamped} stamped in styles.css`);
}
