// src/lib/quiz/generation-progress.ts
//
// A round is generated by one server action that answers only when it is
// finished, so nothing real arrives while it runs. The bar the sheet shows is
// an estimate: it climbs quickly at first, slows as it nears the top, and never
// quite gets there until the drafts land - the same shape as a browser's page
// load bar.

import type { RoundKind } from "./round-kind";

// One text call to the model, roughly proportional to how much it has to write.
const TEXT_BASE_MS = 6_000;
const TEXT_PER_ITEM_MS = 500;

// Songs add a Spotify search per candidate on top of the text call.
const SONG_PER_ITEM_MS = 1_200;

// Pictures are drawn three at a time after the text call, and each batch of
// drawings is the slow part.
const IMAGE_BATCH_SIZE = 3;
const IMAGE_BATCH_MS = 12_000;

// Where the bar sits when the estimate runs out, and the ceiling it creeps
// towards afterwards, so a slow run still looks alive.
const AT_ESTIMATE = 0.8;
const CEILING = 0.96;

export function expectedGenerationMs(kind: RoundKind, count: number): number {
  const items = Math.max(1, count);
  const text = TEXT_BASE_MS + items * TEXT_PER_ITEM_MS;
  if (kind === "song") return text + items * SONG_PER_ITEM_MS;
  if (kind === "picture") return text + Math.ceil(items / IMAGE_BATCH_SIZE) * IMAGE_BATCH_MS;
  return text;
}

/* Fraction complete (0-1) for a run that has been going elapsedMs against an
   expectedMs estimate. Reaches AT_ESTIMATE exactly at the estimate and keeps
   climbing towards CEILING without ever reaching it. */
export function progressAt(elapsedMs: number, expectedMs: number): number {
  if (elapsedMs <= 0 || expectedMs <= 0) return 0;
  const tau = -expectedMs / Math.log(1 - AT_ESTIMATE / CEILING);
  return CEILING * (1 - Math.exp(-elapsedMs / tau));
}

/* What to tell the person while they wait. Only the picture round has a stage
   the timing can distinguish - drawing starts once the subjects are written. */
export function generationStageLabel(kind: RoundKind, elapsedMs: number, count: number): string {
  if (kind === "picture") {
    const textMs = TEXT_BASE_MS + Math.max(1, count) * TEXT_PER_ITEM_MS;
    return elapsedMs < textMs ? "Choosing what to draw…" : "Drawing the pictures…";
  }
  if (kind === "song") return "Picking songs and finding them on Spotify…";
  return "Writing the questions…";
}

export function describeExpectedWait(expectedMs: number): string {
  const seconds = Math.round(expectedMs / 5_000) * 5;
  if (seconds < 60) return `Usually takes about ${Math.max(seconds, 5)} seconds`;
  const minutes = Math.round(seconds / 30) / 2;
  return `Usually takes about ${minutes === 1 ? "a minute" : `${minutes} minutes`}`;
}
