-- ─────────────────────────────────────────────────────────────────────────────
-- Local TEST schema for the bar-app, introspected from the live `pubapp` project.
--
-- NOTE: This mirrors production structure (tables, columns, constraints, indexes,
-- and the bookings_with_events view) but INTENTIONALLY omits Row Level Security.
-- Production auto-enables RLS on every table via an event trigger; for a local
-- test database we leave RLS off so the anon + service-role keys both have full
-- access and tests stay deterministic. Do NOT use this file for production.
--
-- To regenerate an authoritative dump (incl. RLS, triggers, functions) once you
-- have the DB password, run:  npx supabase db dump --linked -f supabase/migrations/<ts>_init.sql
-- ─────────────────────────────────────────────────────────────────────────────

-- Sequences referenced by column defaults (must exist before the tables)
CREATE SEQUENCE IF NOT EXISTS public.company_information_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.promo_content_id_seq;

-- ── Tables ───────────────────────────────────────────────────────────────────

CREATE TABLE public.band_booking_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booker_name text NOT NULL,
  email text NOT NULL,
  phone_no text,
  social_links jsonb DEFAULT '{}'::jsonb,
  video_urls text[] DEFAULT '{}'::text[],
  preferred_dates date[] DEFAULT '{}'::date[],
  notes text,
  status text NOT NULL DEFAULT '''pending''::text'::text,
  admin_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by integer,
  created_by integer,
  selected_date date,
  selected_start_time time without time zone,
  selected_end_time time without time zone,
  type text,
  genre text,
  group_name text,
  payment_amount double precision DEFAULT 0,
  paid_amount double precision DEFAULT 0,
  payment_status text NOT NULL DEFAULT 'unpaid'::text,
  bank_account_no text,
  bank_account_name text,
  bank_sort_code text,
  bank_payment_ref text,
  is_favorite boolean NOT NULL DEFAULT false,
  event_id integer
);

CREATE TABLE public.booking_scores (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  booking_id bigint NOT NULL,
  event_id bigint NOT NULL,
  score double precision DEFAULT '0'::double precision,
  is_winner boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by integer,
  created_by integer
);

CREATE TABLE public.booking_table_mappings (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  booking_id bigint NOT NULL,
  table_id bigint NOT NULL,
  add_seat bigint DEFAULT '0'::bigint,
  location text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  event_id bigint NOT NULL,
  group_name text,
  team_id bigint,
  contact_id bigint NOT NULL,
  group_size bigint NOT NULL DEFAULT '1'::bigint,
  total_amount double precision,
  paid_amount double precision,
  status text NOT NULL,
  special_requests text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  confirmation_sent boolean DEFAULT false,
  internal_notes text,
  updated_by integer,
  marketing_opt_in boolean NOT NULL DEFAULT false,
  payment_status text NOT NULL DEFAULT 'unpaid'::text,
  square_payment_id text,
  square_order_id text,
  created_by integer,
  updated_by_contact_id bigint
);

CREATE TABLE public.company_information (
  id integer NOT NULL DEFAULT nextval('company_information_id_seq'::regclass),
  name text,
  logo_url text,
  address text,
  email text,
  phone text,
  instagram text,
  facebook text,
  twitter text,
  tiktok text,
  youtube text,
  max_capacity integer,
  private_hire_min_capacity integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  description text,
  opening_hours jsonb DEFAULT '{}'::jsonb,
  tagline text,
  tagline_accent text
);

CREATE TABLE public.contacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  full_name text NOT NULL,
  email text NOT NULL,
  country_code text,
  phone_no text,
  birthday date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by integer,
  created_by integer,
  marketing_opt_in boolean NOT NULL DEFAULT false
);

CREATE TABLE public.employees (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  full_name text NOT NULL,
  birthday date,
  email text NOT NULL,
  country_code text,
  phone_no text,
  role text,
  start_date date NOT NULL,
  end_date date,
  status text NOT NULL DEFAULT '''active''::text'::text,
  created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
  updated_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
  created_by integer,
  updated_by integer,
  auth_user_id uuid,
  employment_type text,
  invite_sent_at timestamp with time zone,
  invite_accepted_at timestamp with time zone,
  password_reset_sent_at timestamp with time zone
);

CREATE TABLE public.event_category_playlists (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  events_id integer NOT NULL,
  quiz_category_configs_id integer NOT NULL,
  playlist_id text NOT NULL,
  playlist_url text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.event_subtype_badges (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  event_subtypes_id bigint,
  icon text,
  title text NOT NULL,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.event_subtypes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  modified_at timestamp with time zone NOT NULL DEFAULT now(),
  color text,
  tagline text,
  default_event_title text,
  is_karaoke boolean NOT NULL DEFAULT false,
  is_private boolean NOT NULL DEFAULT false,
  is_music_act boolean NOT NULL DEFAULT false,
  is_quiz boolean NOT NULL DEFAULT false,
  is_bookable boolean NOT NULL DEFAULT false,
  default_booking_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  host_required boolean NOT NULL DEFAULT false,
  seating_required boolean NOT NULL DEFAULT true,
  payment_required boolean NOT NULL DEFAULT false,
  default_payment_amount numeric DEFAULT 0,
  created_by integer,
  modified_by integer,
  event_types_id bigint NOT NULL
);

CREATE TABLE public.event_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NOT NULL,
  description text,
  color text,
  is_karaoke boolean NOT NULL DEFAULT false,
  is_private boolean NOT NULL DEFAULT false,
  is_music_act boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by integer,
  modified_at timestamp with time zone NOT NULL DEFAULT now(),
  modified_by integer
);

CREATE TABLE public.events (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  date date NOT NULL,
  start_time time with time zone,
  end_time time with time zone,
  title text DEFAULT ''::text,
  tagline text DEFAULT ''::text,
  seating_required boolean DEFAULT true,
  payment_amount double precision DEFAULT '0'::double precision,
  host_employee_id smallint,
  event_types_id bigint NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by integer,
  created_by integer,
  is_active boolean DEFAULT true,
  is_fully_booked boolean NOT NULL DEFAULT false,
  group_name text,
  booking_id bigint,
  external_link text,
  is_bookable boolean DEFAULT false,
  booking_config jsonb DEFAULT '{}'::jsonb,
  booking_page_url text,
  karaoke_request_url text,
  event_subtypes_id bigint
);

CREATE TABLE public.gallery_images (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  title text NOT NULL,
  description text,
  image_url text NOT NULL,
  display_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by integer,
  updated_by integer,
  media_type text NOT NULL DEFAULT 'image'::text
);

CREATE TABLE public.generated_quiz_questions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  events_id integer,
  quiz_category_configs_id integer,
  content_text text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.menu_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NOT NULL,
  note text,
  display_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.menu_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  category_id bigint NOT NULL,
  name text NOT NULL,
  price text NOT NULL,
  display_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.past_quiz_questions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  question_text text NOT NULL,
  answer_text text NOT NULL,
  category text,
  asked_on date DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT now(),
  events_id bigint,
  quiz_category_configs_id bigint,
  topic text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by integer,
  updated_by integer,
  release_year smallint,
  spotify_track_id text,
  hint_year smallint,
  image_url text,
  question_no integer,
  answer_text_ext text
);

CREATE TABLE public.private_hire_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  email text NOT NULL,
  phone_no text,
  guest_count integer NOT NULL,
  preferred_date date,
  preferred_start_time time without time zone,
  reason_for_hire text NOT NULL,
  additional_requirements text,
  status text NOT NULL DEFAULT 'pending_review'::text,
  admin_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by integer,
  created_by integer,
  selected_date date,
  selected_start_time time without time zone,
  selected_end_time time without time zone,
  preferred_end_time time without time zone,
  deposit_amount double precision DEFAULT 0,
  paid_amount double precision DEFAULT 0,
  payment_status text NOT NULL DEFAULT 'unpaid'::text,
  square_payment_id text,
  square_order_id text,
  reason text,
  event_id integer
);

CREATE TABLE public.promo_content (
  id bigint NOT NULL DEFAULT nextval('promo_content_id_seq'::regclass),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  title text NOT NULL,
  description text,
  media_url text NOT NULL,
  media_type text NOT NULL DEFAULT 'image'::text,
  external_url text,
  display_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_by bigint,
  updated_by bigint
);

CREATE TABLE public.quiz_category_configs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  category_name text NOT NULL,
  question_count integer,
  points_per_question integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  order_no integer NOT NULL DEFAULT 1,
  include_spotify boolean NOT NULL DEFAULT false,
  short_name text NOT NULL DEFAULT ''::text,
  is_picture boolean NOT NULL DEFAULT false,
  is_higher_lower boolean NOT NULL DEFAULT false
);

CREATE TABLE public.settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by integer,
  updated_by integer,
  max_capacity bigint
);

CREATE TABLE public.specials (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title text NOT NULL,
  description text,
  badges text[] NOT NULL DEFAULT '{}'::text[],
  image_url text,
  start_date date,
  end_date date,
  is_active boolean NOT NULL DEFAULT true,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by integer,
  updated_by integer
);

CREATE TABLE public.tables (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  max_capacity smallint NOT NULL,
  available boolean NOT NULL DEFAULT true,
  description text,
  name text NOT NULL,
  capacity text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by integer,
  updated_by integer
);

CREATE TABLE public.teams (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- ── Constraints (PK / UNIQUE / CHECK / FK) ───────────────────────────────────

ALTER TABLE public.band_booking_requests ADD CONSTRAINT band_booking_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.booking_scores ADD CONSTRAINT booking_scores_pkey PRIMARY KEY (id);
ALTER TABLE public.booking_table_mappings ADD CONSTRAINT booking_table_mappings_pkey PRIMARY KEY (id);
ALTER TABLE public.bookings ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);
ALTER TABLE public.company_information ADD CONSTRAINT company_information_pkey PRIMARY KEY (id);
ALTER TABLE public.contacts ADD CONSTRAINT contacts_email_key UNIQUE (email);
ALTER TABLE public.contacts ADD CONSTRAINT contacts_pkey PRIMARY KEY (id);
ALTER TABLE public.employees ADD CONSTRAINT employees_email_key UNIQUE (email);
ALTER TABLE public.employees ADD CONSTRAINT employees_pkey PRIMARY KEY (id);
ALTER TABLE public.event_category_playlists ADD CONSTRAINT event_category_playlists_events_id_quiz_category_configs_id_key UNIQUE (events_id, quiz_category_configs_id);
ALTER TABLE public.event_category_playlists ADD CONSTRAINT event_category_playlists_pkey PRIMARY KEY (id);
ALTER TABLE public.event_subtype_badges ADD CONSTRAINT event_information_pkey PRIMARY KEY (id);
ALTER TABLE public.event_subtypes ADD CONSTRAINT event_subtypes_pkey PRIMARY KEY (id);
ALTER TABLE public.event_subtypes ADD CONSTRAINT event_subtypes_type_name_key UNIQUE (event_types_id, name);
ALTER TABLE public.event_types ADD CONSTRAINT event_types_pkey PRIMARY KEY (id);
ALTER TABLE public.events ADD CONSTRAINT events_pkey PRIMARY KEY (id);
ALTER TABLE public.gallery_images ADD CONSTRAINT gallery_images_pkey PRIMARY KEY (id);
ALTER TABLE public.generated_quiz_questions ADD CONSTRAINT generated_quiz_questions_pkey PRIMARY KEY (id);
ALTER TABLE public.menu_categories ADD CONSTRAINT menu_categories_pkey PRIMARY KEY (id);
ALTER TABLE public.menu_items ADD CONSTRAINT menu_items_pkey PRIMARY KEY (id);
ALTER TABLE public.past_quiz_questions ADD CONSTRAINT past_quiz_questions_event_cat_no_unique UNIQUE (events_id, quiz_category_configs_id, question_no);
ALTER TABLE public.past_quiz_questions ADD CONSTRAINT past_quiz_questions_pkey PRIMARY KEY (id);
ALTER TABLE public.private_hire_requests ADD CONSTRAINT private_hire_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.promo_content ADD CONSTRAINT promo_content_pkey PRIMARY KEY (id);
ALTER TABLE public.quiz_category_configs ADD CONSTRAINT quiz_category_configs_pkey PRIMARY KEY (id);
ALTER TABLE public.settings ADD CONSTRAINT settings_pkey PRIMARY KEY (id);
ALTER TABLE public.specials ADD CONSTRAINT specials_pkey PRIMARY KEY (id);
ALTER TABLE public.tables ADD CONSTRAINT tables_name_table_key UNIQUE (name);
ALTER TABLE public.tables ADD CONSTRAINT tables_pkey PRIMARY KEY (id);
ALTER TABLE public.teams ADD CONSTRAINT teams_name_key UNIQUE (name);
ALTER TABLE public.teams ADD CONSTRAINT teams_pkey PRIMARY KEY (id);
ALTER TABLE public.band_booking_requests ADD CONSTRAINT band_booking_requests_payment_status_check CHECK ((payment_status = ANY (ARRAY['unpaid'::text, 'paid'::text])));
ALTER TABLE public.band_booking_requests ADD CONSTRAINT band_booking_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'waitlisted'::text, 'cancelled'::text])));
ALTER TABLE public.band_booking_requests ADD CONSTRAINT band_booking_requests_type_check CHECK ((type = ANY (ARRAY['band'::text, 'singer'::text, 'dj'::text])));
ALTER TABLE public.bookings ADD CONSTRAINT bookings_payment_status_check CHECK ((payment_status = ANY (ARRAY['unpaid'::text, 'paid'::text, 'refunded'::text])));
ALTER TABLE public.bookings ADD CONSTRAINT bookings_status_check CHECK ((status = ANY (ARRAY['confirmed'::text, 'waitlisted'::text, 'pending'::text, 'cancelled'::text])));
ALTER TABLE public.employees ADD CONSTRAINT employees_employment_type_check CHECK ((employment_type = ANY (ARRAY['full-time'::text, 'part-time'::text, 'contract'::text, 'probationary'::text, 'seasonal'::text, 'casual'::text])));
ALTER TABLE public.employees ADD CONSTRAINT employees_status_check CHECK ((status = ANY (ARRAY['active'::text, 'inactive'::text, 'leave'::text])));
ALTER TABLE public.private_hire_requests ADD CONSTRAINT private_hire_requests_guest_count_check CHECK ((guest_count > 0));
ALTER TABLE public.private_hire_requests ADD CONSTRAINT private_hire_requests_payment_status_check CHECK ((payment_status = ANY (ARRAY['unpaid'::text, 'paid'::text])));
ALTER TABLE public.private_hire_requests ADD CONSTRAINT private_hire_requests_status_check CHECK ((status = ANY (ARRAY['pending_review'::text, 'confirmed'::text, 'rejected'::text, 'cancelled'::text])));
ALTER TABLE public.band_booking_requests ADD CONSTRAINT band_booking_requests_created_by_fkey FOREIGN KEY (created_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.band_booking_requests ADD CONSTRAINT band_booking_requests_event_id_fkey FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE SET NULL;
ALTER TABLE public.band_booking_requests ADD CONSTRAINT band_booking_requests_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.booking_scores ADD CONSTRAINT booking_scores_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES bookings(id) ON UPDATE CASCADE;
ALTER TABLE public.booking_scores ADD CONSTRAINT booking_scores_created_by_fkey FOREIGN KEY (created_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.booking_scores ADD CONSTRAINT booking_scores_event_id_fkey FOREIGN KEY (event_id) REFERENCES events(id) ON UPDATE CASCADE;
ALTER TABLE public.booking_scores ADD CONSTRAINT booking_scores_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.booking_table_mappings ADD CONSTRAINT booking_table_mappings_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES bookings(id) ON UPDATE CASCADE;
ALTER TABLE public.booking_table_mappings ADD CONSTRAINT booking_table_mappings_table_id_fkey FOREIGN KEY (table_id) REFERENCES tables(id) ON UPDATE CASCADE;
ALTER TABLE public.bookings ADD CONSTRAINT bookings_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id);
ALTER TABLE public.bookings ADD CONSTRAINT bookings_created_by_fkey FOREIGN KEY (created_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.bookings ADD CONSTRAINT bookings_event_id_fkey FOREIGN KEY (event_id) REFERENCES events(id);
ALTER TABLE public.bookings ADD CONSTRAINT bookings_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id);
ALTER TABLE public.bookings ADD CONSTRAINT bookings_updated_by_contact_id_fkey FOREIGN KEY (updated_by_contact_id) REFERENCES contacts(id);
ALTER TABLE public.bookings ADD CONSTRAINT bookings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.contacts ADD CONSTRAINT contacts_created_by_fkey FOREIGN KEY (created_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.contacts ADD CONSTRAINT contacts_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.employees ADD CONSTRAINT employees_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.employees ADD CONSTRAINT employees_created_by_fkey FOREIGN KEY (created_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.employees ADD CONSTRAINT employees_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.event_category_playlists ADD CONSTRAINT event_category_playlists_events_id_fkey FOREIGN KEY (events_id) REFERENCES events(id) ON DELETE CASCADE;
ALTER TABLE public.event_category_playlists ADD CONSTRAINT event_category_playlists_quiz_category_configs_id_fkey FOREIGN KEY (quiz_category_configs_id) REFERENCES quiz_category_configs(id) ON DELETE CASCADE;
ALTER TABLE public.event_subtype_badges ADD CONSTRAINT event_subtype_badges_event_subtypes_id_fkey FOREIGN KEY (event_subtypes_id) REFERENCES event_subtypes(id) ON UPDATE CASCADE;
ALTER TABLE public.event_subtypes ADD CONSTRAINT event_subtypes_event_types_id_fkey FOREIGN KEY (event_types_id) REFERENCES event_types(id) ON DELETE CASCADE;
ALTER TABLE public.events ADD CONSTRAINT events_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE SET NULL;
ALTER TABLE public.events ADD CONSTRAINT events_created_by_fkey FOREIGN KEY (created_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.events ADD CONSTRAINT events_event_subtypes_id_fkey FOREIGN KEY (event_subtypes_id) REFERENCES event_subtypes(id);
ALTER TABLE public.events ADD CONSTRAINT events_event_types_id_fkey FOREIGN KEY (event_types_id) REFERENCES event_types(id);
ALTER TABLE public.events ADD CONSTRAINT events_host_employee_id_fkey FOREIGN KEY (host_employee_id) REFERENCES employees(id) ON UPDATE CASCADE;
ALTER TABLE public.events ADD CONSTRAINT events_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.gallery_images ADD CONSTRAINT gallery_images_created_by_fkey FOREIGN KEY (created_by) REFERENCES employees(id);
ALTER TABLE public.gallery_images ADD CONSTRAINT gallery_images_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES employees(id);
ALTER TABLE public.generated_quiz_questions ADD CONSTRAINT generated_quiz_questions_events_id_fkey FOREIGN KEY (events_id) REFERENCES events(id) ON DELETE CASCADE;
ALTER TABLE public.generated_quiz_questions ADD CONSTRAINT generated_quiz_questions_quiz_category_configs_id_fkey FOREIGN KEY (quiz_category_configs_id) REFERENCES quiz_category_configs(id) ON DELETE CASCADE;
ALTER TABLE public.menu_items ADD CONSTRAINT menu_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES menu_categories(id) ON DELETE CASCADE;
ALTER TABLE public.past_quiz_questions ADD CONSTRAINT past_quiz_questions_created_by_fkey FOREIGN KEY (created_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.past_quiz_questions ADD CONSTRAINT past_quiz_questions_events_id_fkey FOREIGN KEY (events_id) REFERENCES events(id);
ALTER TABLE public.past_quiz_questions ADD CONSTRAINT past_quiz_questions_quiz_category_configs_id_fkey FOREIGN KEY (quiz_category_configs_id) REFERENCES quiz_category_configs(id);
ALTER TABLE public.past_quiz_questions ADD CONSTRAINT past_quiz_questions_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.private_hire_requests ADD CONSTRAINT private_hire_requests_created_by_fkey FOREIGN KEY (created_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.private_hire_requests ADD CONSTRAINT private_hire_requests_event_id_fkey FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE SET NULL;
ALTER TABLE public.private_hire_requests ADD CONSTRAINT private_hire_requests_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.promo_content ADD CONSTRAINT promo_content_created_by_fkey FOREIGN KEY (created_by) REFERENCES employees(id);
ALTER TABLE public.promo_content ADD CONSTRAINT promo_content_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES employees(id);
ALTER TABLE public.settings ADD CONSTRAINT settings_created_by_fkey FOREIGN KEY (created_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.settings ADD CONSTRAINT settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.specials ADD CONSTRAINT specials_created_by_fkey FOREIGN KEY (created_by) REFERENCES employees(id);
ALTER TABLE public.specials ADD CONSTRAINT specials_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES employees(id);
ALTER TABLE public.tables ADD CONSTRAINT tables_created_by_fkey FOREIGN KEY (created_by) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE public.tables ADD CONSTRAINT tables_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES employees(id) ON DELETE SET NULL;

-- ── Secondary indexes ────────────────────────────────────────────────────────

CREATE INDEX event_information_event_types_id_idx ON public.event_subtype_badges USING btree (event_subtypes_id);
CREATE UNIQUE INDEX event_types_name_key ON public.event_types USING btree (lower(name));
CREATE INDEX events_date_idx ON public.events USING btree (date);
CREATE INDEX generated_quiz_questions_event_cat_idx ON public.generated_quiz_questions USING btree (events_id, quiz_category_configs_id);
CREATE INDEX idx_past_questions_date ON public.past_quiz_questions USING btree (asked_on);
CREATE UNIQUE INDEX uq_quiz_category_order_active ON public.quiz_category_configs USING btree (order_no) WHERE (is_active = true);

-- ── View ─────────────────────────────────────────────────────────────────────

CREATE VIEW public.bookings_with_events AS
 SELECT b.id AS booking_id,
    b.status AS booking_status,
    b.group_name AS booking_group_name,
    b.group_size,
    b.total_amount,
    b.paid_amount,
    b.payment_status,
    b.special_requests,
    b.internal_notes,
    b.confirmation_sent,
    b.marketing_opt_in,
    b.square_payment_id,
    b.square_order_id,
    b.created_at AS booking_created_at,
    b.updated_at AS booking_updated_at,
    e.id AS event_id,
    e.date AS event_date,
    e.start_time AS event_start_time,
    e.end_time AS event_end_time,
    e.title AS event_title,
    e.tagline AS event_description,
    e.is_active AS event_is_active,
    e.is_bookable AS event_is_bookable,
    e.is_fully_booked,
    e.payment_amount AS event_payment_amount,
    e.seating_required,
    et.id AS event_type_id,
    et.name AS event_type,
    est.name AS event_sub_type,
    est.color AS badge_color,
    et.color AS type_color,
    c.id AS contact_id,
    c.full_name AS contact_name,
    c.email AS contact_email,
    c.country_code AS contact_country_code,
    c.phone_no AS contact_phone,
    t.id AS team_id,
    t.name AS team_name
   FROM bookings b
     JOIN events e ON e.id = b.event_id
     JOIN event_types et ON et.id = e.event_types_id
     JOIN event_subtypes est ON est.id = e.event_subtypes_id
     JOIN contacts c ON c.id = b.contact_id
     LEFT JOIN teams t ON t.id = b.team_id;

-- ── Grants ───────────────────────────────────────────────────────────────────
-- Hosted Supabase applies these automatically; a hand-built migration must grant
-- explicitly. With RLS off (test DB), these grants give the app's keys full access.

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON ROUTINES TO anon, authenticated, service_role;
