-- Admin-editable copy for the app's transactional emails.
--
-- The scenario list itself lives in code (src/lib/email/scenarios.ts), because
-- every one of these emails is fired by a code path that has to keep working. A
-- row here only *overrides* the built-in copy for one scenario, so deleting a
-- row restores the default rather than leaving a scenario with nothing to send.
--
-- Every slot is nullable and means "not overridden" on its own: editing only the
-- subject keeps whatever copy later ships for the body. Setting is_active false
-- suppresses that email entirely.
--
-- bigint identity to match the other staff-managed tables (merchandise, specials).
-- updated_at is maintained in application code, not by a trigger.
--
-- NOTE: apply the same schema to the production database.

create table if not exists public.email_templates (
  id bigint primary key generated by default as identity,
  scenario_key text not null unique,
  subject text,
  heading text,
  eyebrow text,
  greeting text,
  intro text,
  outro text,
  cta_label text,
  footnote text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by integer references public.employees(id) on delete set null,
  updated_by integer references public.employees(id) on delete set null
);

create index if not exists email_templates_scenario_key_idx
  on public.email_templates (scenario_key);

grant all on public.email_templates to anon, authenticated, service_role;
