-- Seed: hand-picked 2026 trend cards for the Trends Hub.
-- Run once in Supabase SQL editor. Safe to re-run: the signature unique key
-- (same one refreshTrendsAction upserts on) means duplicates are skipped.
-- Change 'Hinckley LE10' if your comparison area is stored differently
-- (check marketing_settings.comparison_area).

insert into public.marketing_trends
  (kind, title, summary, relevance, action, effort, category, source_url, source_name, tags, signature, area, state, fetched_at)
values
  ('advertising', 'Start a "DF Regulars" broadcast channel', 'Instagram broadcast channels are a one-way group chat from the venue to people who opt in. Only 9% of hospitality brands run one, so it still feels exclusive.', 'Reach on the main feed is now algorithmic - a channel is the one place your post lands with every follower who asked for it.', 'Open a broadcast channel called "DF Regulars" this week, pin it in bio, and give members first dibs on quiz tables and band tickets 24 hours before the public post.', 'Easy', 'format', 'https://joliapp.com/blog/state-of-social-2026-hospitality-benchmarks/', 'Joli - State of Social 2026', ARRAY['broadcast channel','regulars','early access','instagram']::text[], 'advertising:start-a-df-regulars-broadcast-channel:joli-state-of-social-2026', 'Hinckley LE10', 'new', now()),
  ('advertising', 'Calm-before vs mid-set contrast Reel', 'Film the empty room at 5pm - chairs up, lights low - then the same angle mid-set with the crowd. Cut them hard together.', 'Reels get roughly double the engagement of static posts in hospitality, and before/after contrast is the format doing best on TikTok right now.', 'Friday: film 5 seconds of the empty stage at soundcheck, 5 seconds of the same shot mid-set, post as a Reel Saturday morning with overlay "5pm vs 10pm".', 'Easy', 'reel', 'https://www.wearebrew.com/digital-marketing-hospitality-blog/restaurant-content-2026/', 'Brew - Restaurant Content 2026', ARRAY['reel','before after','live music','tiktok']::text[], 'advertising:calm-before-vs-mid-set-contrast-reel:brew-restaurant-content-2026', 'Hinckley LE10', 'new', now()),
  ('advertising', 'Write captions and Highlights like searches', 'People now search Instagram and TikTok the way they used to search Google - "live music Hinckley", "karaoke near me", "pub quiz Friday".', '77% of UK Gen Z and 71% of Millennials check a venue''s Instagram or TikTok before deciding where to go.', 'Rename the Highlight covers to "Live Music Hinckley", "Karaoke Mondays", "Quiz Thursdays", "Café" and open every event caption with the same plain search phrase before the clever line.', 'Easy', 'hashtag', 'https://joliapp.com/blog/state-of-social-2026-hospitality-benchmarks/', 'Joli - State of Social 2026', ARRAY['search','captions','highlights','discovery']::text[], 'advertising:write-captions-and-highlights-like-searches:joli-state-of-social-2026', 'Hinckley LE10', 'new', now()),
  ('advertising', '4pm "Tonight" Story, next-morning Reel', 'A fixed rhythm for every event: a Story at 4pm the day of ("tonight: X, doors 8, £10"), then a 15-second highlight Reel the morning after.', 'Events are the strongest footfall driver for pubs on social; the anticipation post and the recap post are the two that convert, and most venues only do one.', 'This week: set a 4pm phone reminder on event days for the Story, and a 10am one the next day for the Reel - same two shots every time so it takes under five minutes.', 'Medium', 'format', 'https://www.wearebrew.com/digital-marketing-hospitality-blog/social-media-ideas-for-pubs-2026/', 'Brew - Social Media Ideas for Pubs 2026', ARRAY['events','stories','reel','routine']::text[], 'advertising:4pm-tonight-story-next-morning-reel:brew-social-media-ideas-for-pubs-2026', 'Hinckley LE10', 'new', now()),
  ('event_idea', 'Get on the list for Everywhere At Once 2027', 'Music Venue Trust''s nationwide grassroots festival: 500+ venues, 1,200 gigs on Glastonbury weekend. 2026 was the first year; venues taking part are recommended to be MVA members.', 'It comes with National Lottery money, national press and a venue-finder map - free marketing you cannot buy at this size.', 'Join the Music Venues Alliance this month and sign up for venue updates at everywherefest.com so DF is on the list when 2027 dates are announced.', 'Medium', 'community', 'https://everywherefest.com/', 'Everywhere At Once', ARRAY['music venue trust','festival','grassroots','june']::text[], 'event_idea:get-on-the-list-for-everywhere-at-once-2027:everywhere-at-once', 'Hinckley LE10', 'new', now()),
  ('event_idea', 'Sell the mix: café, quiz, karaoke, bands', 'MVT''s 2026 report: more than half of UK grassroots venues made no profit last year and employment in the sector fell 22%. Pure gig rooms are the ones closing.', 'DF already has what they don''t - daytime trade, a quiz, karaoke, a DJ night - so the story to tell is "seven nights, four reasons".', 'Put "Café by day. Bands, quiz, karaoke by night." in the bio and on the A-board this week, and run one post that shows all four in a single carousel.', 'Easy', 'community', 'https://www.musicvenuetrust.com/', 'Music Venue Trust annual report 2026', ARRAY['positioning','grassroots','sector','mixed use']::text[], 'event_idea:sell-the-mix-caf-quiz-karaoke-bands:music-venue-trust-annual-report-2026', 'Hinckley LE10', 'new', now())
on conflict (signature) do nothing;
