-- Menu PDF import: one row per parse run, so a run can be reviewed, re-reviewed
-- after a prompt fix, and audited once applied. The extracted menu is kept as
-- `raw_result` rather than the diff, because the diff is recomputed against the
-- live tables at apply time - what the reviewer ticked cannot silently apply a
-- change the menu has moved on from.
create table if not exists public.menu_imports (
  id bigint generated by default as identity primary key,
  file_path text,
  file_name text,
  status text not null default 'parsed'
    check (status in ('parsed', 'applied', 'discarded')),
  raw_result jsonb not null,
  category_count integer not null default 0,
  item_count integer not null default 0,
  applied_count integer not null default 0,
  applied_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  created_by bigint references public.employees(id) on delete set null,
  updated_at timestamp with time zone not null default now(),
  updated_by bigint references public.employees(id) on delete set null
);

create index if not exists menu_imports_created_idx
  on public.menu_imports (created_at desc);

alter table public.menu_imports enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'menu_imports'
      and policyname = 'Allow authenticated full'
  ) then
    create policy "Allow authenticated full" on public.menu_imports
      for all to authenticated using (true) with check (true);
  end if;
end $$;

-- A private bucket, unlike the public `gallery` one - an uploaded supplier menu
-- is internal paperwork, not something to serve from a public URL.
do $$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'storage' and table_name = 'buckets'
  ) then
    insert into storage.buckets (id, name, public)
    values ('menu-uploads', 'menu-uploads', false)
    on conflict (id) do nothing;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'storage'
        and tablename = 'objects'
        and policyname = 'Menu uploads readable by authenticated'
    ) then
      create policy "Menu uploads readable by authenticated" on storage.objects
        for select to authenticated using (bucket_id = 'menu-uploads');
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'storage'
        and tablename = 'objects'
        and policyname = 'Menu uploads writable by authenticated'
    ) then
      create policy "Menu uploads writable by authenticated" on storage.objects
        for insert to authenticated with check (bucket_id = 'menu-uploads');
    end if;
  end if;
end $$;
