-- Email subscriptions for Market Night alerts, the third channel beside push
-- and SMS. A row is created when the guest asks for a code and only counts
-- once verified_at is set; the code is stored hashed with a short expiry and
-- an attempt counter. manage_token is handed to the browser that verified the
-- address and is required to change or stop its alerts; it also signs the
-- unsubscribe link in every email.
create table if not exists public.market_email_subscriptions (
  id                     bigint generated by default as identity primary key,
  email                  text not null unique,
  manage_token           uuid not null default gen_random_uuid(),
  watched_instrument_ids bigint[] not null default '{}'::bigint[],
  verified_at            timestamptz,
  verify_code_hash       text,
  verify_expires_at      timestamptz,
  verify_attempts        integer not null default 0,
  code_sent_at           timestamptz,
  opted_out_at           timestamptz,
  sent_night             date,
  sent_count             integer not null default 0,
  last_error             text,
  failed_at              timestamptz,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);
