-- Web Push subscriptions for Market Night phone alerts. One row per browser
-- push endpoint; an empty watched list means "alert me on every drop".
-- Written only by the server (service role) from the public market page.
create table if not exists public.market_push_subscriptions (
  id                     bigint generated by default as identity primary key,
  endpoint               text not null unique,
  p256dh                 text not null,
  auth                   text not null,
  watched_instrument_ids bigint[] not null default '{}'::bigint[],
  user_agent             text,
  last_error             text,
  failed_at              timestamptz,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);
