create or replace function public.dashboard_schema_ddl(only_tables text[] default null)
 returns text
 language plpgsql
 stable security definer
 set search_path to 'public'
as $function$
declare
  out text := '';
  r record;
  c record;
  cols text;
  cons text;
  line text;
  seen_views text[] := '{}';
  remaining int;
  progressed boolean;
  roles_list text := 'anon, authenticated, service_role';
  wanted boolean;
begin
  out := out || '-- Schema export generated ' || to_char(now(), 'YYYY-MM-DD HH24:MI:SS TZ') || E'\n'
             || '-- Recreates the public schema of this project: sequences, functions, tables, constraints, indexes, views, triggers, RLS policies, grants and comments.' || E'\n'
             || '-- Run it in the SQL editor of a fresh Supabase project. Data is not included; import the CSV export afterwards.' || E'\n'
             || (case when only_tables is null then '' else '-- Limited to: ' || array_to_string(only_tables, ', ') || E'\n' end)
             || E'\nbegin;\nset check_function_bodies = off;\n\n';

  -- extensions (Supabase-managed ones are already present in every project)
  out := out || E'-- Extensions\n';
  for r in select extname from pg_extension where extname not in ('plpgsql','pg_stat_statements','supabase_vault','pg_graphql','hypopg','index_advisor','pgsodium','pgjwt') order by extname loop
    out := out || format('create extension if not exists %I with schema extensions;', r.extname) || E'\n';
  end loop;

  -- stand-alone sequences (identity sequences are created by their columns)
  out := out || E'\n-- Sequences\n';
  for r in select s.sequencename, s.data_type, s.start_value, s.min_value, s.max_value, s.increment_by, s.cycle
           from pg_sequences s
           where s.schemaname = 'public'
             and not exists (select 1 from pg_depend d join pg_class sc on sc.oid = d.objid where sc.relname = s.sequencename and sc.relkind = 'S' and d.deptype = 'i')
           order by s.sequencename loop
    out := out || format('create sequence if not exists public.%I as %s increment by %s minvalue %s maxvalue %s start with %s %s;',
                         r.sequencename, r.data_type, r.increment_by, r.min_value, r.max_value, r.start_value, case when r.cycle then 'cycle' else 'no cycle' end) || E'\n';
  end loop;

  -- functions
  out := out || E'\n-- Functions\n';
  for r in select p.oid, p.proname from pg_proc p join pg_namespace n on n.oid = p.pronamespace
           where n.nspname = 'public' and p.prokind in ('f','p') and p.proname <> 'dashboard_schema_ddl' order by p.proname loop
    out := out || pg_get_functiondef(r.oid) || E';\n\n';
  end loop;

  -- tables
  out := out || E'-- Tables\n';
  for r in select cl.oid, cl.relname from pg_class cl join pg_namespace n on n.oid = cl.relnamespace
           where n.nspname = 'public' and cl.relkind in ('r','p') and (only_tables is null or cl.relname = any(only_tables)) order by cl.relname loop
    cols := '';
    for c in select a.attname, format_type(a.atttypid, a.atttypmod) as typ, a.attnotnull, a.attidentity, a.attgenerated,
                    pg_get_expr(d.adbin, d.adrelid) as def,
                    (select seqstart from pg_sequence sq join pg_depend dp on dp.objid = sq.seqrelid where dp.refobjid = a.attrelid and dp.refobjsubid = a.attnum and dp.deptype = 'i' limit 1) as idstart,
                    case when a.attcollation <> 0 and a.attcollation <> (select t.typcollation from pg_type t where t.oid = a.atttypid) then (select quote_ident(co.collname) from pg_collation co where co.oid = a.attcollation) end as coll
             from pg_attribute a left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
             where a.attrelid = r.oid and a.attnum > 0 and not a.attisdropped order by a.attnum loop
      line := '  ' || quote_ident(c.attname) || ' ' || c.typ
              || coalesce(' collate ' || c.coll, '')
              || case when c.attnotnull then ' not null' else '' end
              || case when c.attidentity = 'a' then ' generated always as identity' || case when c.idstart is not null and c.idstart <> 1 then format(' (start with %s)', c.idstart) else '' end
                      when c.attidentity = 'd' then ' generated by default as identity' || case when c.idstart is not null and c.idstart <> 1 then format(' (start with %s)', c.idstart) else '' end
                      when c.attgenerated = 's' then ' generated always as (' || c.def || ') stored'
                      when c.def is not null then ' default ' || c.def
                      else '' end;
      cols := cols || case when cols = '' then '' else E',\n' end || line;
    end loop;
    cons := '';
    for c in select con.conname, pg_get_constraintdef(con.oid) as def from pg_constraint con
             where con.conrelid = r.oid and con.contype in ('p','u','c','x') order by con.contype, con.conname loop
      cons := cons || E',\n  constraint ' || quote_ident(c.conname) || ' ' || c.def;
    end loop;
    out := out || format('create table if not exists public.%I (', r.relname) || E'\n' || cols || cons || E'\n);\n';
    for c in select s.relname as seq, a.attname from pg_depend d join pg_class s on s.oid = d.objid join pg_attribute a on a.attrelid = d.refobjid and a.attnum = d.refobjsubid
             where d.refobjid = r.oid and s.relkind = 'S' and d.deptype = 'a' loop
      out := out || format('alter sequence public.%I owned by public.%I.%I;', c.seq, r.relname, c.attname) || E'\n';
    end loop;
    out := out || E'\n';
  end loop;

  -- foreign keys
  out := out || E'-- Foreign keys\n';
  for r in select cl.relname, con.conname, pg_get_constraintdef(con.oid) as def
           from pg_constraint con join pg_class cl on cl.oid = con.conrelid join pg_namespace n on n.oid = cl.relnamespace
           where n.nspname = 'public' and con.contype = 'f' and (only_tables is null or cl.relname = any(only_tables))
           order by cl.relname, con.conname loop
    out := out || format('alter table public.%I add constraint %I %s;', r.relname, r.conname, r.def) || E'\n';
  end loop;

  -- indexes not backing a constraint
  out := out || E'\n-- Indexes\n';
  for r in select pg_get_indexdef(i.indexrelid) as def, cl.relname
           from pg_index i join pg_class cl on cl.oid = i.indrelid join pg_namespace n on n.oid = cl.relnamespace
           where n.nspname = 'public' and not exists (select 1 from pg_constraint k where k.conindid = i.indexrelid)
             and (only_tables is null or cl.relname = any(only_tables))
           order by cl.relname, def loop
    out := out || replace(r.def, 'CREATE INDEX', 'CREATE INDEX IF NOT EXISTS') || E';\n';
  end loop;

  -- views in dependency order
  out := out || E'\n-- Views\n';
  select count(*) into remaining from pg_class v join pg_namespace n on n.oid = v.relnamespace where n.nspname = 'public' and v.relkind in ('v','m') and (only_tables is null or v.relname = any(only_tables));
  while remaining > 0 loop
    progressed := false;
    for r in select v.oid, v.relname, v.relkind from pg_class v join pg_namespace n on n.oid = v.relnamespace
             where n.nspname = 'public' and v.relkind in ('v','m') and (only_tables is null or v.relname = any(only_tables)) and not (v.relname = any(seen_views)) order by v.relname loop
      if not exists (
        select 1 from pg_depend d join pg_rewrite rw on rw.oid = d.objid join pg_class dep on dep.oid = d.refobjid join pg_namespace dn on dn.oid = dep.relnamespace
        where rw.ev_class = r.oid and dep.relkind in ('v','m') and dep.oid <> r.oid and dn.nspname = 'public' and not (dep.relname = any(seen_views))
      ) then
        out := out || format('create or replace %s public.%I as', case when r.relkind = 'm' then 'materialized view' else 'view' end, r.relname) || E'\n' || pg_get_viewdef(r.oid, true) || E'\n\n';
        seen_views := seen_views || r.relname; remaining := remaining - 1; progressed := true;
      end if;
    end loop;
    exit when not progressed;
  end loop;

  -- triggers
  out := out || E'-- Triggers\n';
  for r in select pg_get_triggerdef(t.oid) as def from pg_trigger t join pg_class cl on cl.oid = t.tgrelid join pg_namespace n on n.oid = cl.relnamespace
           where n.nspname = 'public' and not t.tgisinternal and (only_tables is null or cl.relname = any(only_tables)) order by cl.relname, t.tgname loop
    out := out || r.def || E';\n';
  end loop;
  if only_tables is null then
    for r in select e.evtname, e.evtevent, e.evttags, p.proname from pg_event_trigger e join pg_proc p on p.oid = e.evtfoid join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' loop
      out := out || format('create event trigger %I on %s%s execute function public.%I();', r.evtname, r.evtevent,
                           case when r.evttags is null then '' else ' when tag in (' || (select string_agg(quote_literal(x), ', ') from unnest(r.evttags) x) || ')' end, r.proname) || E'\n';
    end loop;
  end if;

  -- row level security and policies
  out := out || E'\n-- Row level security\n';
  for r in select cl.relname, cl.relrowsecurity, cl.relforcerowsecurity from pg_class cl join pg_namespace n on n.oid = cl.relnamespace
           where n.nspname = 'public' and cl.relkind in ('r','p') and (only_tables is null or cl.relname = any(only_tables)) order by cl.relname loop
    out := out || format('alter table public.%I %s row level security;', r.relname, case when r.relrowsecurity then 'enable' else 'disable' end) || E'\n';
    if r.relforcerowsecurity then out := out || format('alter table public.%I force row level security;', r.relname) || E'\n'; end if;
  end loop;
  out := out || E'\n-- Policies\n';
  for r in select p.tablename, p.policyname, p.permissive, p.roles, p.cmd, p.qual, p.with_check from pg_policies p
           where p.schemaname = 'public' and (only_tables is null or p.tablename = any(only_tables)) order by p.tablename, p.policyname loop
    out := out || format('create policy %I on public.%I as %s for %s to %s%s%s;', r.policyname, r.tablename, lower(r.permissive), lower(r.cmd),
                         (select string_agg(case when x = 'public' then 'public' else quote_ident(x) end, ', ') from unnest(r.roles) x),
                         case when r.qual is not null then ' using (' || r.qual || ')' else '' end,
                         case when r.with_check is not null then ' with check (' || r.with_check || ')' else '' end) || E'\n';
  end loop;

  -- grants
  out := out || E'\n-- Grants\n';
  for r in select g.table_name, g.grantee, string_agg(lower(g.privilege_type), ', ' order by g.privilege_type) as privs
           from information_schema.role_table_grants g
           where g.table_schema = 'public' and g.grantee in ('anon','authenticated','service_role') and (only_tables is null or g.table_name = any(only_tables))
           group by g.table_name, g.grantee order by g.table_name, g.grantee loop
    out := out || format('grant %s on table public.%I to %I;', r.privs, r.table_name, r.grantee) || E'\n';
  end loop;
  if only_tables is null then
    out := out || format('grant usage, select, update on all sequences in schema public to %s;', roles_list) || E'\n';
    out := out || format('grant execute on all functions in schema public to %s;', roles_list) || E'\n';
  end if;

  -- comments
  out := out || E'\n-- Comments\n';
  for r in select cl.relname, obj_description(cl.oid, 'pg_class') as cm, cl.relkind from pg_class cl join pg_namespace n on n.oid = cl.relnamespace
           where n.nspname = 'public' and cl.relkind in ('r','p','v','m') and obj_description(cl.oid, 'pg_class') is not null and (only_tables is null or cl.relname = any(only_tables)) loop
    out := out || format('comment on %s public.%I is %L;', case when r.relkind in ('v','m') then 'view' else 'table' end, r.relname, r.cm) || E'\n';
  end loop;
  for r in select cl.relname, a.attname, col_description(a.attrelid, a.attnum) as cm from pg_attribute a join pg_class cl on cl.oid = a.attrelid join pg_namespace n on n.oid = cl.relnamespace
           where n.nspname = 'public' and cl.relkind in ('r','p','v','m') and a.attnum > 0 and not a.attisdropped and col_description(a.attrelid, a.attnum) is not null and (only_tables is null or cl.relname = any(only_tables)) loop
    out := out || format('comment on column public.%I.%I is %L;', r.relname, r.attname, r.cm) || E'\n';
  end loop;

  out := out || E'\ncommit;\n';
  return out;
end
$function$;

grant execute on function public.dashboard_schema_ddl(text[]) to anon, authenticated, service_role;
