-- Simulated till sales for the live market. The tick reads demand from
-- Square's completed orders (see src/lib/market/tick.ts); this table is a
-- second demand feed so staff can "sell" drinks from the admin without a
-- till, sandbox catalog or real customers. One row per simulated sale;
-- the tick that consumes a row stamps consumed_tick_no so nothing is
-- counted twice and there is an audit trail of what was faked and when.

create table if not exists public.market_sim_sales (
  id               bigint generated by default as identity primary key,
  session_id       bigint not null references public.market_sessions(id) on delete cascade,
  instrument_id    bigint not null references public.market_instruments(id) on delete cascade,
  units            numeric not null check (units > 0),
  source           text not null default 'manual',  -- 'manual' | 'busy_round'
  created_by       bigint references public.employees(id) on delete set null,
  created_at       timestamptz not null default now(),
  consumed_tick_no integer
);

-- The tick only ever asks for the unconsumed rows of one session.
create index if not exists market_sim_sales_pending_idx
  on public.market_sim_sales (session_id, instrument_id)
  where consumed_tick_no is null;

-- RLS off on the local test DB; prod auto-applies its own.
grant all on public.market_sim_sales to anon, authenticated, service_role;
