-- Drinks stock market ("Market Night") - schema.
--
-- On market nights the drinks menu trades like a stock exchange: real Square
-- POS sales push prices up, quiet drinks drift back toward base, and Square
-- inventory counts drive low/out-of-stock alerts. A session snapshots the
-- menu prices it opens with, so ending a night never touches menu data and
-- the board's history survives menu edits.
--
-- Prices are advanced by the tick-on-read endpoint (/api/market/state), not a
-- cron: the first request after the interval elapses wins a compare-and-swap
-- on market_sessions.last_tick_at and runs the engine.
-- All additive + idempotent.

-- ── menu_item_prices → Square catalog variation mapping ─────────────────────
-- A Square variation is a serve (pint / half / bottle), so demand attribution
-- lives at the serve level, beside the money it moves.
alter table public.menu_item_prices
  add column if not exists square_variation_id text;

create index if not exists menu_item_prices_square_variation_idx
  on public.menu_item_prices (square_variation_id)
  where square_variation_id is not null;

-- ── market_sessions - one row per market night ───────────────────────────────
create table if not exists public.market_sessions (
  id               bigint generated by default as identity primary key,
  status           text not null default 'live',   -- 'live' | 'ended'
  config           jsonb not null default '{}'::jsonb,  -- engine knobs; merged over code defaults
  tick_no          integer not null default 0,
  last_tick_at     timestamptz,
  orders_watermark timestamptz,                    -- Square closedAt high-water mark for demand
  crash_until_tick integer,                        -- manual crash active while tick_no < this
  started_at       timestamptz not null default now(),
  ended_at         timestamptz,
  created_at       timestamptz not null default now(),
  created_by       bigint references public.employees(id) on delete set null
);

-- Only one market can trade at a time.
create unique index if not exists market_sessions_one_live_idx
  on public.market_sessions (status)
  where status = 'live';

-- ── market_instruments - one tradeable serve per session ─────────────────────
create table if not exists public.market_instruments (
  id                  bigint generated by default as identity primary key,
  session_id          bigint not null references public.market_sessions(id) on delete cascade,
  menu_item_price_id  bigint not null references public.menu_item_prices(id) on delete cascade,
  menu_item_id        bigint not null references public.menu_items(id) on delete cascade,
  display_name        text not null,               -- snapshot of the item name at open
  serve               text not null,               -- snapshot
  base_price          numeric(6,2) not null,       -- menu price at open; reversion target
  opening_price       numeric(6,2) not null,
  current_price       numeric(6,2) not null,
  last_notified_price numeric(6,2) not null,       -- move-alert anchor; resets when an alert fires
  demand_units        numeric not null default 0,  -- decaying buy-pressure score
  stock_state         text not null default 'ok',  -- 'ok' | 'low' | 'out' (effective, published)
  stock_override      text,                        -- manual admin call: 'ok' | 'low' | 'out'; wins over inventory
  square_variation_id text,                        -- snapshot of the mapping at open
  updated_at          timestamptz not null default now(),
  unique (session_id, menu_item_price_id)
);

create index if not exists market_instruments_session_idx
  on public.market_instruments (session_id);

-- ── market_ticks - price history (sparklines + retry idempotency) ────────────
create table if not exists public.market_ticks (
  id            bigint generated by default as identity primary key,
  session_id    bigint not null references public.market_sessions(id) on delete cascade,
  instrument_id bigint not null references public.market_instruments(id) on delete cascade,
  tick_no       integer not null,
  price         numeric(6,2) not null,
  demand_units  numeric not null default 0,
  created_at    timestamptz not null default now(),
  unique (instrument_id, tick_no)
);

create index if not exists market_ticks_instrument_idx
  on public.market_ticks (instrument_id, tick_no desc);

-- ── market_events - the alert feed phones subscribe to ───────────────────────
create table if not exists public.market_events (
  id            bigint generated by default as identity primary key,
  session_id    bigint not null references public.market_sessions(id) on delete cascade,
  instrument_id bigint references public.market_instruments(id) on delete cascade,
  kind          text not null,  -- 'price_drop' | 'surge' | 'crash' | 'low_stock' | 'out_of_stock' | 'restock'
  payload       jsonb not null default '{}'::jsonb,  -- {name, serve, from, to, pct}
  created_at    timestamptz not null default now()
);

create index if not exists market_events_session_idx
  on public.market_events (session_id, id);

-- ── Grants (RLS off on the local test DB; prod auto-applies its own) ──────────
grant all on public.market_sessions    to anon, authenticated, service_role;
grant all on public.market_instruments to anon, authenticated, service_role;
grant all on public.market_ticks       to anon, authenticated, service_role;
grant all on public.market_events      to anon, authenticated, service_role;
