-- Which AI provider, model and endpoint each part of the app uses, chosen on
-- Settings > AI settings. One row.
--
-- providers: keyed by provider id from the code registry
--   (src/lib/ai/providers/registry.ts), each { label, api_base_url, active,
--   created_at, updated_at, created_by, updated_by }. A null api_base_url means
--   the provider's built-in default. API keys are never stored here; they stay
--   in the environment.
--
-- areas: keyed by area key from src/lib/ai/areas.ts, each { label, kind,
--   provider, model, api_base_url, active, created_at, updated_at, created_by,
--   updated_by }. api_base_url overrides the provider's URL for that area only.
--
-- Both maps are reconciled against the code registries whenever the settings
-- page loads or saves: a new area or provider in code gets an entry, and an
-- entry whose code has gone is kept but marked inactive. The *_by values are
-- employees.id, matching the row-level audit columns.
create table if not exists public.ai_settings (
  id bigint generated by default as identity primary key,
  providers jsonb not null default '{}'::jsonb,
  areas jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by bigint references public.employees(id) on delete set null,
  updated_by bigint references public.employees(id) on delete set null,
  constraint ai_settings_providers_object check (jsonb_typeof(providers) = 'object'),
  constraint ai_settings_areas_object check (jsonb_typeof(areas) = 'object')
);
