-- SMS subscriptions for Market Night alerts, the text-message twin of
-- market_push_subscriptions. One row per verified UK mobile; an empty watched
-- list means "alert me on every drop". manage_token is handed to the phone
-- that verified the number and is required to change or stop its alerts.
-- sent_night / sent_count cap how many texts one phone gets per trading night.
create table if not exists public.market_sms_subscriptions (
  id                     bigint generated by default as identity primary key,
  phone                  text not null unique,
  manage_token           uuid not null default gen_random_uuid(),
  watched_instrument_ids bigint[] not null default '{}'::bigint[],
  opted_out_at           timestamptz,
  sent_night             date,
  sent_count             integer not null default 0,
  last_error             text,
  failed_at              timestamptz,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);
