-- Merchandise: branded goods the venue shows off on the public home page
-- (t-shirts, totes, glassware). Showcase only - there is no basket, no Square
-- catalogue link and no stock tracking. `price` is a display label so guests
-- know what to expect at the bar; the app never charges it.
--
-- display_order is maintained as a contiguous 1..N sequence over the ACTIVE
-- rows only, resequenced in application code (see src/lib/merchandise-order.ts).
-- Inactive rows always sit at 0. There is deliberately no unique constraint or
-- trigger enforcing this - the invariant is an application concern, and this
-- schema has no triggers or functions anywhere.
--
-- bigint identity PK and the audit quad follow the specials convention;
-- updated_at is maintained in application code, not by a trigger. Images live
-- in the public `gallery` storage bucket under merchandise/.
--
-- NOTE: apply the same schema to the production database.

create table if not exists public.merchandise (
  id bigint primary key generated by default as identity,
  name text not null,
  description text,
  image_url text,
  price numeric(10,2),
  is_active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by integer references public.employees(id) on delete set null,
  updated_by integer references public.employees(id) on delete set null
);

create index if not exists merchandise_display_order_idx on public.merchandise (display_order);
