-- Square price-sync leg for the drinks market.
-- Pairs with src/lib/market/square-price-sync.ts. Runs against the tables that
-- already exist in prod (market_sessions / market_instruments, bigint ids).

-- Per-instrument sync state --------------------------------------------------
alter table public.market_instruments
  -- Real price held in Square when the session opened; put back when it ends.
  -- Written once per instrument (see captureSquareOriginalPrices).
  add column if not exists square_original_price numeric(6,2),
  -- Last price Square acknowledged. Board/phone should show THIS as the
  -- headline number; current_price is the pending move. Differs = "dirty".
  add column if not exists square_synced_price   numeric(6,2),
  add column if not exists square_sync_error     text;

-- The tick's dirty-row query: linked instruments whose price moved since the
-- last successful write.
create index if not exists market_instruments_square_dirty_idx
  on public.market_instruments (session_id)
  where square_variation_id is not null
    and (square_synced_price is null or square_synced_price <> current_price);

-- Per-session kill switch (demo the board on the TV without touching the till).
alter table public.market_sessions
  add column if not exists square_sync_enabled boolean not null default true;

-- Audit log: one row per variation per push ----------------------------------
create table if not exists public.market_square_sync_log (
  id                  bigint generated by default as identity primary key,
  session_id          bigint references public.market_sessions (id) on delete cascade,
  instrument_id       bigint references public.market_instruments (id) on delete set null,
  square_variation_id text,
  price_before        numeric(6,2),
  price_after         numeric(6,2),
  version_before      bigint,
  version_after       bigint,
  cause               text not null check (cause in ('tick', 'restore')),
  error               text,
  created_at          timestamptz not null default now()
);

create index if not exists market_square_sync_log_session_idx
  on public.market_square_sync_log (session_id, created_at desc);

-- Staff can read the log from the settings page; only the server writes it.
alter table public.market_square_sync_log enable row level security;

drop policy if exists "market_square_sync_log_select" on public.market_square_sync_log;
create policy "market_square_sync_log_select"
  on public.market_square_sync_log for select
  to authenticated using (true);

drop policy if exists "market_square_sync_log_insert" on public.market_square_sync_log;
create policy "market_square_sync_log_insert"
  on public.market_square_sync_log for insert
  to authenticated with check (true);
