-- Questions a host turned down in the round sheet - left unpicked when the
-- round was added, or swapped out - that the generator must never offer again
-- for that quiz category, on any quiz night.
--
-- generated_quiz_questions cannot carry this: it is scoped to one event and is
-- cleared when that event is switched off.
--
-- content_text is what the host saw (the question, "Artist - Title" for a song,
-- the answer for a picture card); content_key is its normalised form from
-- src/lib/quiz/exclusion-key.ts, which is what matching runs on.
create table if not exists public.quiz_question_exclusions (
  id bigint generated by default as identity primary key,
  quiz_category_configs_id bigint not null
    references public.quiz_category_configs(id) on delete cascade,
  content_text text not null,
  content_key text not null,
  source_event_id bigint references public.events(id) on delete set null,
  created_by bigint references public.employees(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint quiz_question_exclusions_category_key_unique
    unique (quiz_category_configs_id, content_key)
);

alter table public.quiz_question_exclusions enable row level security;

drop policy if exists "Allow authenticated full" on public.quiz_question_exclusions;
create policy "Allow authenticated full" on public.quiz_question_exclusions
  for all to authenticated using (true) with check (true);
