-- WhatsApp subscriptions for Market Night alerts, the fourth channel beside
-- push, SMS and email. Same shape as market_sms_subscriptions: one row per
-- verified number (E.164), a manage_token the subscribing phone keeps, a
-- stop_code for the link in every message, and a per-night send counter.
create table if not exists public.market_whatsapp_subscriptions (
  id                     bigint generated by default as identity primary key,
  phone                  text not null unique,
  manage_token           uuid not null default gen_random_uuid(),
  stop_code              text not null unique
                           default substr(replace(gen_random_uuid()::text, '-', ''), 1, 12),
  watched_instrument_ids bigint[] not null default '{}'::bigint[],
  opted_out_at           timestamptz,
  sent_night             date,
  sent_count             integer not null default 0,
  last_error             text,
  failed_at              timestamptz,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);
